

- hosts: workstation

  # ----------------------------------------------------
  # Sublime Apt File must exist on the system to use Apt
  # ----------------------------------------------------
  vars:
    - sublime_apt_file: /etc/apt/sources.list.d/sublime-text.list

  tasks:

    # --------------------------------------------------
    # Ensure apt repository key is present on the system
    # --------------------------------------------------
    - apt_key:
        url: "https://download.sublimetext.com/sublimehq-pub.gpg"
        state: present

    # ---------------------------------------------------------
    # Ensure that the Sublime repository is properly configured
    #   -> Check to see whether Apt repository exists
    #   -> Suppress error output for expected status codes
    # ---------------------------------------------------------
    - name: Ensure Sublime apt repository is properly configured
      command: "test -e {{ sublime_apt_file }}"
      register: sublime_apt_exists
      ignore_errors: True
      changed_when: sublime_apt_exists.rc != 0 and sublime_apt_exists.rc != 1
      failed_when: sublime_apt_exists.rc != 0 and sublime_apt_exists.rc != 1
      become: True
      become_user: nobody

    - name: Add Sublime Apt repository if it does not exist
      copy: 
        content: "deb https://download.sublimetext.com/ apt/stable/" 
        dest: "{{ sublime_apt_file }}"
        owner: root
        group: root
        mode: 644
      when: sublime_apt_exists.rc != 0
      become: True
      become_method: sudo

    - name: Update Apt Cache if Sublime repository was added
      apt: 
        update_cache: yes
      when: sublime_apt_exists.rc != 0
      become: True
      become_method: sudo

    # --------------------------------------------
    # Ensure Sublime Text is present on the system
    # --------------------------------------------
    - name: Sublime Text is installed
      apt: 
        pkg: sublime-text
        state: latest
      become: True
      become_method: sudo
