

- hosts: workstation

  # ---------------------------------------------------
  # Chrome Apt File must exist on the system to use Apt
  # ---------------------------------------------------
  vars:
    - chrome_apt_file: /etc/apt/sources.list.d/google-chrome.list

  tasks:
    
    # --------------------------------------------------
    # Ensure Chrome Apt repository key is present on the system
    # --------------------------------------------------
    - name: Chrome Apt repository is present
      apt_key:
        url: "https://dl-ssl.google.com/linux/linux_signing_key.pub"
        state: present

    # ----------------------------------------------------
    # Ensure Chrome Apt repository is properly configured
    #   -> Check to see whether Apt repository exists
    #   -> Suppress error output for expected status codes
    # ----------------------------------------------------
    - name: Ensure Chrome apt repository is properly configured
      command: "test -e {{ chrome_apt_file }}"
      register: chrome_apt_exists
      ignore_errors: True
      changed_when: chrome_apt_exists.rc != 0 and chrome_apt_exists.rc != 1
      failed_when: chrome_apt_exists.rc != 0 and chrome_apt_exists.rc != 1
      become: True
      become_user: nobody

    - name: Add Chrome Apt repository if it does not exist
      copy:
        content: "deb http://dl.google.com/linux/chrome/deb stable main" 
        dest: "{{ chrome_apt_file }}" 
        owner: root
        group: root
        mode: 644
      when: chrome_apt_exists.rc != 0
      become: True
      become_user: sudo

    - name: Update Apt Cache if Chrome repository was added
      apt:
        update_cache: yes
      when: chrome_apt_exists.rc != 0
      become: True
      become_method: sudo

    # ---------------------------------------------
    # Ensure Google Chrome is present on the system
    # ---------------------------------------------
    - name: Google Chrome is installed
      apt:
        pkg: google-chrome-stable
        state: latest
      become: True
      become_method: sudo

